
# Loads default set of integrations. Do not remove.
default_config:

# Text to speech
tts:
  - platform: google_translate

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

http:
  use_x_forwarded_for: true
  trusted_proxies:
    - 10.80.0.0/24
    - 172.0.0.0/8

recorder:
  db_url: !secret db_url
  purge_keep_days: 90

