volumes:
  homeassistant:
  homeassistant-db:

services:
  homeassistant-db:
    restart: unless-stopped
    image: postgres:13
    container_name: homeassistant-db
    environment:
      TZ: Europe/Madrid
      POSTGRES_DB: homeassistant
      POSTGRES_USER: hauser
      POSTGRES_PASSWORD: hapass
    ports:
      - 127.0.0.1:5432:5432
    volumes:
      - homeassistant-db:/var/lib/postgresql/data
    dns:
      - 10.80.0.2

  homeassistant:
    depends_on:
      - homeassistant-db
    container_name: homeassistant
    image: homeassistant/home-assistant:latest
    environment:
      - TZ=Europe/Madrid
      - PUID=1000
      - PGID=1000
    healthcheck:
      test: 'curl -m 90 -sLf http://localhost:8123 || date >> /config/healthcheck' #| pkill -9 python3'
      interval: 90s
      timeout: 60s
      retries: 2
    volumes:
      - /run/dbus:/run/dbus:ro
      - ./config/home-assistant:/config
      - homeassistant:/config/.storage
    network_mode: host
    restart: unless-stopped
    dns:
      - 10.80.0.2

  # appdaemon:
  #   container_name: appdaemon
  #   image: acockburn/appdaemon:latest
  #   environment:
  #     - TZ=Europe/Madrid
  #     - PUID=1000
  #     - PGID=1000
  #     - HA_TOKEN
  #   healthcheck:
  #     test: 'curl -m 90 -sLf http://localhost:5050 || date >> /conf/healthcheck'
  #     interval: 90s
  #     timeout: 60s
  #     retries: 2
  #   volumes:
  #     - ./config/appdaemon:/conf
  #   depends_on:
  #     - homeassistant
  #   network_mode: host
  #   restart: unless-stopped
  #   dns:
  #     - 10.80.0.2
