volumes:
  homeassistant:
  appdaemon:

services:
  homeassistant:
    container_name: home-assistant
    image: homeassistant/home-assistant:latest
    environment:
      - TZ=Europe/Madrid
      - PUID=1000
      - PGID=1000
    healthcheck:
      test: 'curl -m 90 -sLf http://localhost:8123 || date >> /config/healthcheck' #| pkill -9 python3'
      interval: 90s
      timeout: 60s
      retries: 2
    volumes:
      - /run/dbus:/run/dbus:ro
      - homeassistant:/config
    network_mode: host
    restart: unless-stopped
    dns:
      - 10.80.0.2

  appdaemon:
    container_name: appdaemon
    image: acockburn/appdaemon:latest
    environment:
      - TZ=Europe/Madrid
      - PUID=1000
      - PGID=1000
      - HA_TOKEN
    healthcheck:
      test: 'curl -m 90 -sLf http://localhost:5050 || date >> /conf/healthcheck'
      interval: 90s
      timeout: 60s
      retries: 2
    volumes:
      - appdaemon:/conf
    depends_on:
      - homeassistant
    network_mode: host
    restart: unless-stopped
    dns:
      - 10.80.0.2
