# TODO: merge edge branch and change stack to point to master
services:
  homeassistant:
    container_name: home-assistant
    image: homeassistant/home-assistant:latest
    environment:
      - TZ=Europe/Madrid
    healthcheck:
      test: 'curl -m 90 -sLf http://localhost:${HA_PORT:-8123} || date >> /config/healthcheck' #| pkill -9 python3'
      interval: 90s
      timeout: 60s
      retries: 2
    volumes:
      - /run/dbus:/run/dbus:ro
      - $DOCKER_DATA_PATH/$ENV/home-assistant/home-assistant/config:/config
    network_mode: host
    restart: unless-stopped
    dns:
      - 10.80.0.2

  appdaemon:
    container_name: appdaemon
    image: acockburn/appdaemon:latest
    environment:
      - TZ=Europe/Madrid
      - HA_TOKEN
    healthcheck:
      test: 'curl -m 90 -sLf http://localhost:${DA_PORT:-5050} || date >> /conf/healthcheck'
      interval: 90s
      timeout: 60s
      retries: 2
    volumes:
      - $DOCKER_DATA_PATH/$ENV/home-assistant/appdaemon/conf:/conf
    depends_on:
      - homeassistant
    network_mode: host
    restart: unless-stopped
    dns:
      - 10.80.0.2
