#test1:
#  module: some_app
#  class: your_class_name
#  switchID: light.luz_cocina
#  lightID: light.luz_escritorio

bathroom-lights:
  module: bathroom_lights
  class: BathroomLights
  door_sensor: binary_sensor.bathroom_door
  motion_sensor: binary_sensor.bathroom_sensor
  lights:
    - light.luz_bano_1
    - light.luz_bano_2
    - light.luz_bano_3
    - light.luz_bano_4

disco-lights:
  module: disco_lights
  class: DiscoLights
  switch: light.virtual_rgbcct
  lights:
    - light.luz_salon_0
    - light.luz_salon_1
    - light.luz_salon_2
    - light.luz_salon_3
    - light.luz_salon_4
    - light.luz_salon_5
    - light.luz_salon_6
    - light.luz_salon_7
    - light.luz_salon_8
    - light.luz_salon_9
    - light.luz_pie_salon
